import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import test from "node:test";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

import * as TypeScriptApi from "../dist/index.js";

const execFileAsync = promisify(execFile);
const expectedRevision = "6f33baead8b88166c4b2cf94af41763412e3c751";
const baselinePath = process.env.STRUTTURE_JS_BASELINE_PATH
  ? path.resolve(process.env.STRUTTURE_JS_BASELINE_PATH)
  : path.resolve(import.meta.dirname, "..", "..", "strutture-js");
const expectedExports = [
  "APPLICATION_CATALOG",
  "AXIAL_PILE_BASE_RESISTANCE_METHODS",
  "AXIAL_PILE_CAPACITY_REFERENCE",
  "AXIAL_PILE_CAPACITY_RESULT_SCHEMA_VERSION",
  "AXIAL_PILE_EFFECTIVE_STRESS_COEFFICIENT_MODELS",
  "AXIAL_PILE_LOAD_DIRECTIONS",
  "AXIAL_PILE_LOAD_SCENARIO_SCHEMA_VERSION",
  "AXIAL_PILE_RESISTANCE_CONVERSION_MODELS",
  "AXIAL_PILE_SHAFT_RESISTANCE_METHODS",
  "STRUT_AND_TIE_MEMBER_TYPES",
  "DEEP_FOUNDATION_DISPLACEMENT_CLASSES",
  "DEEP_FOUNDATION_ELEMENT_TYPES",
  "DEEP_FOUNDATION_GEOMETRY_MODELS",
  "DEEP_FOUNDATION_MODEL_SCHEMA_VERSION",
  "GEOTECHNICAL_DESIGN_SITUATION_SCHEMA_VERSION",
  "GEOTECHNICAL_DESIGN_SITUATION_TYPES",
  "GEOTECHNICAL_DRAINAGE_CONDITIONS",
  "GEOTECHNICAL_INTERNAL_UNITS",
  "GEOTECHNICAL_LIMIT_STATES",
  "GEOTECHNICAL_SEISMIC_MODELS",
  "GEOTECHNICAL_TIME_CONDITIONS",
  "GROUND_MODEL_SCHEMA_VERSION",
  "GROUND_PROFILE_SCHEMA_VERSION",
  "GROUND_SECTION_2D_SCHEMA_VERSION",
  "SOIL_DEFORMATION_MODELS",
  "SOIL_DRAINAGE_CONDITIONS",
  "SOIL_MODULUS_DEFINITIONS",
  "SOIL_PARAMETER_BASES",
  "SOIL_SETTLEMENT_COMPONENTS",
  "SOIL_STRENGTH_MODELS",
  "SOIL_STRUCTURE_INTERFACE_MODELS",
  "SOIL_STRUCTURE_INTERFACE_SCHEMA_VERSION",
  "SHALLOW_FOUNDATION_ACTION_BASES",
  "SHALLOW_FOUNDATION_ACTION_STATE_SCHEMA_VERSION",
  "SHALLOW_FOUNDATION_MODEL_SCHEMA_VERSION",
  "SHALLOW_FOUNDATION_SHAPES",
  "LATERAL_PILE_BEHAVIOR_CLASSIFICATIONS",
  "LATERAL_PILE_BROMS_REFERENCE",
  "LATERAL_PILE_CAPACITY_METHODS",
  "LATERAL_PILE_CAPACITY_RESULT_SCHEMA_VERSION",
  "LATERAL_PILE_HEAD_CONDITIONS",
  "LATERAL_PILE_LOAD_SCENARIO_SCHEMA_VERSION",
  "LATERAL_PILE_RESISTANCE_CONVERSION_MODELS",
  "LATERAL_PILE_SOIL_BRANCHES",
  "LATERAL_PILE_ACTION_REFERENCE_POINTS",
  "LATERAL_PILE_END_RESTRAINTS",
  "LATERAL_PILE_RESPONSE_METHODS",
  "LATERAL_PILE_RESPONSE_SCENARIO_SCHEMA_VERSION",
  "LATERAL_PILE_SOIL_RESPONSE_MODELS",
  "LATERAL_PILE_PY_REFERENCE",
  "LATERAL_PILE_PY_RESULT_SCHEMA_VERSION",
  "PILE_TRANSFER_CURVE_MODELS",
  "PILE_TRANSFER_EXTRAPOLATION_MODELS",
  "PILE_TRANSFER_LAW_KINDS",
  "PILE_TRANSFER_LAW_SCHEMA_VERSION",
  "WALL_SOIL_REACTION_EXTRAPOLATION_MODELS",
  "WALL_SOIL_REACTION_LAW_SCHEMA_VERSION",
  "WALL_SOIL_REACTION_MODELS",
  "STEEL_PROFILE_CATALOG_UNITS",
  "STEEL_PROFILE_FAMILIES",
  "STEEL_PROFILE_SECTION_DATABASE",
  "STEEL_PROFILE_SECTION_NAMES",
  "AxialPileCapacityAnalysis",
  "AxialPileLoadScenario",
  "AxialMember2D",
  "AccidentalAction",
  "Action",
  "AreaLoad",
  "ApplicationRegistry",
  "ClimaticAction",
  "BEAM_SUPPORT_PRESETS",
  "CYCLIC_MASONRY_INTERNAL_UNITS",
  "DeepFoundationModel",
  "GeotechnicalDeepFoundationApplication",
  "GeotechnicalDesignSituation",
  "GroundModel",
  "GroundProfile",
  "GroundSection2D",
  "SoilMaterial",
  "SoilStructureInterface",
  "SlopeSurfaceSurcharge2D",
  "ShallowFoundationActionState",
  "ShallowFoundationModel",
  "SHALLOW_FOUNDATION_BASE_UPLIFT_TREATMENTS",
  "SHALLOW_FOUNDATION_BEARING_METHODS",
  "SHALLOW_FOUNDATION_BEARING_SELECTIONS",
  "SHALLOW_FOUNDATION_ULS_RESULT_SCHEMA_VERSION",
  "ShallowFoundationUltimateLimitStateAnalysis",
  "calculateShallowFoundationBearingCapacity",
  "calculateShallowFoundationEffectiveGeometry",
  "calculateShallowFoundationSlidingResistance",
  "LateralPileLoadScenario",
  "LateralPileCapacityAnalysis",
  "RETAINING_WALL_BASE_UPLIFT_MODELS",
  "RETAINING_WALL_LOAD_SCENARIO_SCHEMA_VERSION",
  "RETAINING_WALL_MODEL_SCHEMA_VERSION",
  "RETAINING_WALL_SEISMIC_DIRECTIONS",
  "RETAINING_WALL_TYPES",
  "RetainingWallLoadScenario",
  "RetainingWallModel",
  "RETAINING_WALL_ANALYSIS_RESULT_SCHEMA_VERSION",
  "RetainingWallAnalysis",
  "calculateRetainingWallPolygonProperties",
  "PileTransferLaw",
  "LateralPileResponseScenario",
  "LateralPileBeamOnSpringsAnalysis",
  "WallSoilReactionLaw",
  "coulombActiveEarthPressureCoefficient",
  "coulombPassiveEarthPressureCoefficient",
  "jakyAtRestCoefficient",
  "mononobeOkabeActiveEarthPressureCoefficient",
  "rankineEarthPressureCoefficients",
  "EARTH_PRESSURE_METHODS",
  "EARTH_PRESSURE_STATES",
  "LateralEarthPressureAnalysis",
  "GROUND_ANCHOR_BOND_CATALOG",
  "GROUND_ANCHOR_BOND_CATALOG_IDS",
  "GROUND_ANCHOR_BOND_CATALOG_REFERENCE",
  "getGroundAnchorBondCatalogEntry",
  "listGroundAnchorBondCatalogEntries",
  "EMBEDDED_RETAINING_WALL_LOADING_CONDITIONS",
  "EMBEDDED_RETAINING_WALL_REFERENCES",
  "EMBEDDED_RETAINING_WALL_RESULT_SCHEMA_VERSION",
  "EMBEDDED_RETAINING_WALL_SCENARIO_SCHEMA_VERSION",
  "EMBEDDED_RETAINING_WALL_SUPPORT_BEHAVIORS",
  "EMBEDDED_RETAINING_WALL_SUPPORT_TYPES",
  "EmbeddedRetainingWallScenario",
  "EmbeddedRetainingWallAnalysis",
  "SLOPE_STABILITY_METHODS",
  "CIRCULAR_SLOPE_STABILITY_RESULT_SCHEMA_VERSION",
  "SLOPE_STABILITY_ANALYSIS_MODES",
  "CircularSlopeStabilityAnalysis",
  "SLOPE_SLICE_DISCRETIZATION_2D_SCHEMA_VERSION",
  "SLOPE_SURFACE_SURCHARGE_2D_SCHEMA_VERSION",
  "ordinaryMethodOfSlices",
  "simplifiedBishop",
  "spencerMethod",
  "SlopeSliceDiscretizer2D",
  "VerticalStressProfile",
  "IDENTITY_RESISTANCE_AXIS_TRANSFORMATION",
  "BaseMaterial",
  "BandedLinearSolver",
  "BeamElement",
  "BeamLinePreprocessor2D",
  "BeamSectionActionVerifier",
  "BeamSystem",
  "CalculationResult",
  "CIRCULAR_SLIP_SURFACE_2D_SCHEMA_VERSION",
  "EMBEDDED_RETAINING_WALL_END_RESTRAINTS",
  "EMBEDDED_RETAINING_WALL_MODEL_SCHEMA_VERSION",
  "EMBEDDED_RETAINING_WALL_TYPES",
  "GROUND_ANCHOR_CORROSION_CLASSES",
  "GROUND_ANCHOR_HORIZONTAL_DIRECTIONS",
  "GROUND_ANCHOR_MODEL_SCHEMA_VERSION",
  "GROUND_ANCHOR_BOND_RESISTANCE_MODELS",
  "GROUND_ANCHOR_DEMAND_SOURCES",
  "GROUND_ANCHOR_DESIGN_REFERENCE",
  "GROUND_ANCHOR_DESIGN_RESULT_SCHEMA_VERSION",
  "GROUND_ANCHOR_DESIGN_SCENARIO_SCHEMA_VERSION",
  "GROUND_ANCHOR_FAILURE_SURFACE_MODELS",
  "GROUND_ANCHOR_FHWA_CRITERIA",
  "GROUND_ANCHOR_GROUND_CLASSES",
  "GROUND_ANCHOR_STABILITY_ACTION_2D_SCHEMA_VERSION",
  "GROUND_ANCHOR_STABILITY_FORCE_MODELS",
  "GROUND_ANCHOR_STABILITY_REFERENCE",
  "GROUND_ANCHOR_TEST_TYPES",
  "GROUND_ANCHOR_TENDON_TYPES",
  "PRESSURE_DIAGRAM_2D_SCHEMA_VERSION",
  "PORE_PRESSURE_FIELD_2D_MODELS",
  "PORE_PRESSURE_FIELD_2D_SCHEMA_VERSION",
  "Combination",
  "CircularSection",
  "CompositeSection",
  "CompositeSectionComponent",
  "ConcreteMaterial",
  "ConcreteNoTensionLaw",
  "ConcreteParabolaRectangleLaw",
  "ConcreteStressBlockLaw",
  "ConcreteTriangularRectangleLaw",
  "CyclicMasonryCompressionMaterial",
  "CyclicMasonryPierAnalysis2D",
  "CyclicMasonryPier2D",
  "CyclicMasonryShearMaterial",
  "MasonryFiberInterface2D",
  "cyclicMasonryPierHistoryToCsv",
  "CrackedSectionBeamModel",
  "CrackedSectionDeflectionAnalysis",
  "CircularSlipSurface2D",
  "EmbeddedRetainingWallModel",
  "GroundAnchorModel",
  "GroundAnchorDesignScenario",
  "GroundAnchorAnalysis",
  "GroundAnchorStabilityAction2D",
  "PressureDiagram2D",
  "integratePressureSegments",
  "groundAnchorDemandFromEmbeddedWallResult",
  "PorePressureField2D",
  "CrossSection",
  "GLOBAL_FEM_LINE_ACTION_COMPONENTS",
  "GLOBAL_FEM_SECTION_CUT_COMPONENTS",
  "GLOBAL_FEM_SHELL_RESULTANT_COMPONENTS",
  "DenseLinearSolver",
  "DisplacementControlNonlinearStaticSolver2D",
  "DesignCodeContext",
  "DistributedLoad",
  "ElementPointLoad",
  "DofRegistry",
  "DEFAULT_SECTION_ROTATION",
  "ElasticBeamSectionProvider",
  "ExistingMaterial",
  "ExistingMasonryMaterial",
  "GlulamTimberMaterial",
  "FEM_ANALYSIS_CAPABILITY_KEYS",
  "FEM_ANALYSIS_TYPES",
  "FEM_CONTRACT_SCHEMAS",
  "FEM_ELEMENT_CAPABILITY_KEYS",
  "FEM_RESULT_CAPABILITY_KEYS",
  "FEM_RESULT_STATUS_VALUES",
  "FoundationBeamAnalysis",
  "FoundationBeamFemBuilder",
  "FoundationBeamModel",
  "EXISTING_MATERIAL_CONFIDENCE_LEVELS",
  "GLOBAL_FEM_CONTRACT_VERSION",
  "GLOBAL_FEM_REQUIRED_UNIT_KEYS",
  "DEFAULT_GLOBAL_FEM_CLASSIFICATION_POLICY",
  "GLOBAL_FEM_CLASSIFICATION_PROPOSAL_VERSION",
  "GLOBAL_FEM_DEMAND_SET_VERSION",
  "GLOBAL_FEM_POSTPROCESSING_PROFILES",
  "GLOBAL_FEM_POSTPROCESSING_PROFILE_VALUES",
  "GLOBAL_FEM_READINESS_ASSESSMENTS",
  "GLOBAL_FEM_READINESS_ASSESSMENT_VALUES",
  "GLOBAL_FEM_READINESS_REPORT_VERSION",
  "FORCE_UNIT_FACTORS",
  "FemAssembler2D",
  "FrameElement2DEulerBernoulli",
  "FrameElement2DTimoshenko",
  "FrameElement2DTimoshenkoRigidOffsets",
  "GlobalFemPostProcessingApplication",
  "IllinoisRootSolver",
  "ImposedAction",
  "HyperstaticDeflectionIteration",
  "KinematicConstraintReducer2D",
  "LENGTH_UNIT_FACTORS",
  "LineLoad",
  "LinearStaticSolver2D",
  "Load",
  "LoadCase",
  "LoadCombination",
  "MasonryMaterial",
  "MohrCoulombModel",
  "NTC2018_ACTION_COMBINATION_FACTORS",
  "NTC2018_ACTION_PARTIAL_FACTORS",
  "NTC2018_CASE_BY_CASE_COMBINATION_CATEGORIES",
  "NTC2018_CONCRETE_CLASSES",
  "NTC2018_ANALYSIS_METHOD",
  "NTC2018_BASE_Q_FACTORS",
  "NTC2018_DEFAULT_DURATION_CLASS_BY_ACTION",
  "NTC2018_ELEVATION_REGULARITY",
  "NTC2018_EXISTING_MATERIAL_KNOWLEDGE_LEVELS",
  "NTC2018_LOAD_DURATION_CLASSES",
  "NTC2018_OVERSTRENGTH_FACTORS",
  "NTC2018_PLAN_REGULARITY",
  "NTC2018_REGULARITY_REDUCTION",
  "NTC2018_REINFORCEMENT_STEEL_GRADES",
  "NTC2018_STRUCTURAL_BEHAVIOR",
  "NTC2018_STRUCTURAL_BEHAVIOR_REFERENCES",
  "NTC2018_STRUCTURAL_TYPE",
  "NTC2018_TIMBER_KMOD",
  "NodalLoad",
  "Node",
  "PolygonSection",
  "PointLoad",
  "VolumeLoad",
  "PUNCHING_ACTION_SCHEMA_VERSION",
  "PUNCHING_CONNECTION_SCHEMA_VERSION",
  "PUNCHING_CONTROL_PERIMETER_SCHEMA_VERSION",
  "PUNCHING_VERIFICATION_REQUEST_SCHEMA_VERSION",
  "PunchingActionState",
  "PunchingConnectionModel",
  "PunchingControlPerimeter",
  "PunchingVerification",
  "PunchingVerificationRequest",
  "RCBiaxialDomainBuilder",
  "RCMomentCurvatureAnalyzer",
  "RC_PLATE_ANALYSIS_TYPES",
  "RC_PUNCHING_DESIGN_CODE_IDS",
  "RC_PUNCHING_DESIGN_CODE_ID_VALUES",
  "RC_PUNCHING_PARAMETER_PROFILES",
  "RCServiceStressSolver",
  "RCUniaxialDomainBuilder",
  "RCUltimateSectionSolver",
  "RC_DEFLECTION_PERFORMANCE_PROFILES",
  "RCrackedDeflectionApplication",
  "RC_STRUT_AND_TIE_SUPPORTED_CODE",
  "ReinforcedConcreteBeamColumnJoint3DModel",
  "ReinforcedConcreteBeamColumnJoint3DVerification",
  "RESULT_STATUS",
  "RESULT_STATUS_FAILED",
  "RESULT_STATUS_NOT_ANALYZED",
  "RESULT_STATUS_NOT_IMPLEMENTED",
  "RESULT_STATUS_NOT_SUPPORTED",
  "RESULT_STATUS_NOT_VERIFIED",
  "RESULT_STATUS_OK",
  "RESULT_STATUS_VALUES",
  "RectangularSection",
  "RectangularFootingContactAnalysis",
  "ReinforcedConcreteSection",
  "ReinforcedConcreteSectionApplication",
  "ReinforcedConcreteBeamDetailingVerification",
  "ReinforcedConcreteBeamSectionProvider",
  "SteelBeamSectionProvider",
  "TimberBeamSectionProvider",
  "XlamBeamSectionProvider",
  "XlamPanelSection",
  "ReinforcedConcreteBeamVerification",
  "ReinforcedConcreteBeamColumnJointApplication",
  "ReinforcedConcreteBeamColumnJointModel",
  "ReinforcedConcreteBeamColumnJointVerification",
  "ReinforcedConcreteColumnApplication",
  "ReinforcedConcreteColumnDetailingVerification",
  "ReinforcedConcreteColumnModel",
  "ReinforcedConcreteColumnVerification",
  "ReinforcedConcreteIsolatedFootingApplication",
  "ReinforcedConcreteIsolatedFootingModel",
  "ReinforcedConcreteIsolatedFootingVerification",
  "ReinforcedConcreteFoundationBeamApplication",
  "ReinforcedConcreteFoundationBeamModel",
  "ReinforcedConcretePlateApplication",
  "ReinforcedConcretePlateModel",
  "ReinforcedConcretePlateVerification",
  "ReinforcedConcretePunchingApplication",
  "ReinforcedConcreteSectionModel",
  "ReinforcedConcreteServiceabilityVerification",
  "ReinforcedConcreteShearVerification",
  "ReinforcedConcreteSectionVerification",
  "ReinforcedConcreteStrutAndTieApplication",
  "ReinforcedConcreteStrutAndTieModel",
  "ReinforcedConcreteStrutAndTieVerification",
  "RcBuildingVerificationApplication",
  "ReinforcedConcreteTorsionVerification",
  "ReinforcementBar",
  "SectionFiberDiscretizer",
  "SectionMomentCurvatureCurve",
  "ShearConnector",
  "SlidingStrengthModel",
  "SteelElasticPerfectlyPlasticLaw",
  "SteelElasticLaw",
  "SteelElasticPlasticHardeningLaw",
  "SteelMaterial",
  "SteelCompoundProfileSection",
  "SteelProfileSection",
  "SingleBeamAnalysis",
  "SingleBeamFemBuilder",
  "SingleBeamModel",
  "StrutAndTieAnalysis2D",
  "StrutAndTieModel2D",
  "StrainField",
  "StructuralApplication",
  "StructuralElement",
  "SolidTimberMaterial",
  "TimberMaterial",
  "XlamMaterial",
  "SLOPE_MOVEMENT_DIRECTIONS",
  "Support",
  "TSection",
  "TECNARIA_CONNECTOR_CATALOG",
  "TECNARIA_CONNECTOR_TYPES",
  "TecnariaConnector",
  "getTecnariaConnectorData",
  "TimberDowelConnector",
  "TurnsekSheppardModel",
  "VerificationResult",
  "assertExplicitUnitSystem",
  "assertPositiveCheckValue",
  "characteristicValueFromExistingMean",
  "convertUnitProperties",
  "createLongitudinalReinforcementLayout",
  "createMasonryShearStrengthModel",
  "collectConcurrentLineElementActionStates",
  "collectConcurrentMemberActionStates",
  "collectConcurrentJointActionStates",
  "collectConcurrentSectionCutStates",
  "collectConcurrentSupportReactionStates",
  "collectConcurrentSurfaceResultantStates",
  "createFemCapabilitiesContract",
  "createFemEntityMappingContract",
  "createGlobalFemAnalysisContract",
  "createGlobalFemContractSet",
  "createGlobalFemModelContract",
  "createGlobalFemResultContract",
  "createCapacityDesignAssessment",
  "createDiaphragmAssessment",
  "createDisplacementAssessment",
  "createNTC2018AccidentalAction",
  "createNTC2018ConcreteMaterial",
  "createNTC2018LinearDynamicAssessment",
  "createNTC2018PermanentAction",
  "createNTC2018RegularityAssessment",
  "createNTC2018ReinforcementSteelMaterial",
  "createNTC2018SeismicAction",
  "createNTC2018SnowAction",
  "createNTC2018StructuralBehavior",
  "createNTC2018ThermalAction",
  "createNTC2018VariableAction",
  "createNTC2018WindAction",
  "createTecnariaConnector",
  "createElasticBeamSectionProvider",
  "createReinforcedConcreteBeamSectionProvider",
  "createSteelBeamSectionProvider",
  "createDoubleAngleOpposedSection",
  "createDoubleUPNBackToBackSection",
  "createSteelCompoundProfileSection",
  "createSteelProfileSection",
  "createTimberBeamSectionProvider",
  "createXlamBeamSectionProvider",
  "createXlamPanelSection",
  "createScaServiceDeflectionAnalysisResult",
  "createServiceDeflectionAnalysisResult",
  "createPlateStripSection",
  "createUnitResolver",
  "governingCheck",
  "getRcPunchingDesignCodeManifest",
  "getSteelProfileSectionData",
  "getNTC2018ActionCombinationFactors",
  "getNTC2018ActionPartialFactors",
  "getNTC2018LoadDurationClass",
  "getNTC2018LoadDurationDefinition",
  "getNTC2018RcBuildingCoverage",
  "getNTC2018TimberKmod",
  "getXlamPanelProduct",
  "isFinitePositive",
  "isResultStatus",
  "integrateFootingPressureStrip",
  "listSteelProfileSectionsByFamily",
  "listXlamPanelProducts",
  "normalizeUnitSystem",
  "normalizeExistingMaterialKnowledgeLevel",
  "normalizeGlobalFemClassificationPolicy",
  "normalizeNTC2018StructuralBehavior",
  "normalizeNTC2018StructuralType",
  "normalizeSectionRotation",
  "principalSecondMoments",
  "resolveExistingMaterialState",
  "resolveBeamSupportPreset",
  "resolvePunchingTransferFromJointActions",
  "resolvePrincipalSectionFrame",
  "selectNTC2018OverstrengthFactors",
  "selectNTC2018AllowedAnalysisMethods",
  "selectNTC2018BaseQFactor",
  "resolveNTC2018AlphaRatio",
  "resolveNTC2018GoverningLoadDuration",
  "registerXlamPanelProduct",
  "splitPrincipalActions",
  "round",
  "runRcServiceDeflectionAnalysis",
  "runFoundationSystemVerifications",
  "runSlabSystemVerifications",
  "runWallSystemVerifications",
  "runScaRcDeflectionAnalysis",
  "rotatePlateMoments",
  "rotatePlateShear",
  "rotateSecondMoments",
  "calculateSectionMassProperties",
  "amplifyNTC2018DiaphragmActions",
  "auditNTC2018RcDesignBasis",
  "checkNonDissipativeAdmissibility",
  "computeBeamCapacityShear",
  "computeColumnCapacityShear",
  "computeJointCapacityShear",
  "computeNTC2018EffectiveQFactor",
  "computePDeltaCoefficient",
  "computeSeismicJointWidth",
  "computeStoreyDrift",
  "evaluateNTC2018ElevationRegularity",
  "evaluateNTC2018PlanRegularity",
  "evaluateNTC2018RcBuildingCompleteness",
  "calculateEn1992AnchorageLength",
  "calculateEn1992DesignBondStrength",
  "calculateEn1992LocalBearingResistance",
  "calculateEn1992NodalDesignStrength",
  "calculateEn1992ShrinkageCurvature",
  "calculateEn1992StrutAndTieNuPrime",
  "calculateEn1992StrutDesignStrength",
  "calculateEn1992TieResistance",
  "calculateNTC2018EffectiveJointWidth",
  "calculateNTC2018JointCompressionCapacity",
  "calculateNTC2018JointShearDemand",
  "calculateNTC2018JointTensionReinforcement",
  "classifyNTC2018JointConfinement",
  "ntc2018JointOverstrengthFactor",
  "uniqueStrings",
  "utilizationCheck",
  "validateFemCapabilitiesContract",
  "validateFemEntityMappingContract",
  "validateGlobalFemAnalysisContract",
  "validateGlobalFemContractSet",
  "validateGlobalFemModelContract",
  "validateGlobalFemResultContract",
  "classifyGlobalFemStructuralEntities",
  "verifyBeamColumnHierarchy",
  "verifyNTC2018AccidentalEccentricities",
  "verifyNTC2018ModalMassParticipation",
  "verifyPDelta",
  "verifyStoreyDisplacements",
  "verifyStoreyDrift",
  "evaluateGlobalFemVerificationReadiness",
  "extractGlobalFemDemands",
  "filterConcurrentFemStates",
  "projectFoundationReactionStatesToResistanceAxes",
  "projectJointActionStatesToResistanceAxes",
  "projectLineActionStateToResistanceAxes",
  "projectMemberActionStatesToResistanceAxes",
  "projectSectionCutStateToResistanceAxes",
  "projectShellResultantStateToResistanceAxes",
  "projectSlabResultantStatesToResistanceAxes",
  "projectSupportReactionStateToResistanceAxes",
  "projectWallSectionCutStatesToResistanceAxes",
  "validateResistanceAxisTransformation",
  "validateSurfaceResistanceAxisTransformation",
  "verifyBeamSectionActions",
  "verifyPlateBending",
  "verifyPlateServiceability",
  "verifyPlateShear",
  "verifyPlateSlenderness",
  "verifyPunching",
  "woodArmer",
  "NTC2018_SHEAR_WALL_REFERENCES",
  "NTC2018_BEAM_COLUMN_JOINT_TENSION_METHODS",
  "NTC2018_BEAM_COLUMN_JOINT_TYPES",
  "NTC2018_CAPACITY_DESIGN_REFERENCES",
  "NTC2018_RC_BUILDING_CAPABILITIES",
  "NTC2018_RC_COVERAGE_STATUS",
  "NTC2018_RC_TRACEABILITY_STATUS",
  "NTC2018_DIAPHRAGM_FORCE_FACTOR",
  "NTC2018_DIAPHRAGM_REFERENCES",
  "NTC2018_DISPLACEMENT_REFERENCES",
  "NTC2018_DRIFT_INFILL_CATEGORY",
  "NTC2018_DRIFT_LIMITS",
  "NTC2018_LINEAR_DYNAMIC_REFERENCES",
  "NTC2018_PDELTA_THRESHOLDS",
  "NTC2018_REGULARITY_REFERENCES",
  "EN1992_STRUT_AND_TIE_NODE_TYPES",
  "EN1992_STRUT_STRENGTH_MODELS",
  "NTC2018_WALL_SYSTEM_REFERENCES",
  "WALL_BIAXIAL_REFERENCE",
  "computeMixedSystemWallShearEnvelope",
  "computeWallBoundaryLength",
  "computeWallCapacityShear",
  "computeWallConfinementOmegaWd",
  "computeWallCriticalZoneHeight",
  "computeWallEffectiveFlangeWidth",
  "computeWallMomentShift",
  "computeWeaklyReinforcedWallAxialDemandRange",
  "computeWeaklyReinforcedWallShearDemand",
  "createCouplingBeamAssessment",
  "createWallHeightSystemAssessment",
  "createWallSectionAssessment",
  "verifyWallBiaxialBending",
  "verifyWallBoundaryConfinement",
  "verifyWallCurvatureDuctility",
  "verifyWallGeneralDetailing",
  "verifyWallShear",
  "PermanentAction",
  "SeismicAction",
  "SnowAction",
  "ThermalAction",
  "TrafficAction",
  "VariableAction",
  "WindAction",
].sort();

const { stdout: revisionOutput } = await execFileAsync("git", [
  "-C",
  baselinePath,
  "rev-parse",
  "HEAD",
]);
const { stdout: statusOutput } = await execFileAsync("git", [
  "-C",
  baselinePath,
  "status",
  "--porcelain",
]);
const revision = revisionOutput.trim();
assert.equal(revision, expectedRevision, "Compatibility test loaded the wrong source revision.");
assert.equal(statusOutput.trim(), "", "Compatibility test requires a clean source worktree.");

const JavaScriptApi = (await import(
  pathToFileURL(path.join(baselinePath, "src", "index.js")).href
)) as Record<string, unknown>;

function baselineExport<TExport>(name: string): TExport {
  const value = JavaScriptApi[name];
  assert.notEqual(value, undefined, `The baseline is missing ${name}.`);
  return value as TExport;
}

void test("the migrated runtime exports exactly the declared public subset", () => {
  assert.deepEqual(Object.keys(TypeScriptApi).sort(), expectedExports);
  for (const name of expectedExports) {
    assert.ok(Object.hasOwn(JavaScriptApi, name), `The source baseline does not export ${name}.`);
  }
});

void test("result constants and serialized DTO behavior match the live baseline", () => {
  assert.deepEqual(TypeScriptApi.RESULT_STATUS, baselineExport("RESULT_STATUS"));
  assert.deepEqual(TypeScriptApi.RESULT_STATUS_VALUES, baselineExport("RESULT_STATUS_VALUES"));

  const JavaScriptCalculationResult =
    baselineExport<typeof TypeScriptApi.CalculationResult>("CalculationResult");
  const JavaScriptVerificationResult =
    baselineExport<typeof TypeScriptApi.VerificationResult>("VerificationResult");
  const options = {
    applicationId: "parity",
    assumptions: ["assigned"],
    metadata: { method: "parity" },
    outputs: { value: 4 },
    status: TypeScriptApi.RESULT_STATUS.OK,
    summary: "Compared",
    warnings: ["warning"],
  };
  const verificationOptions = {
    ...options,
    capacity: 8,
    checks: [{ id: "capacity", ok: true, utilizationRatio: 0.5 }],
    demand: 4,
    utilizationRatio: 0.5,
  };

  assert.deepEqual(
    new TypeScriptApi.CalculationResult(options).toJSON(),
    new JavaScriptCalculationResult(options).toJSON(),
  );
  assert.deepEqual(
    new TypeScriptApi.VerificationResult(verificationOptions).toJSON(),
    new JavaScriptVerificationResult(verificationOptions).toJSON(),
  );
  assert.equal(
    new TypeScriptApi.VerificationResult(verificationOptions).isVerified(),
    new JavaScriptVerificationResult(verificationOptions).isVerified(),
  );
});

void test("unit conversion values and metadata match the live baseline", () => {
  const createJavaScriptResolver =
    baselineExport<typeof TypeScriptApi.createUnitResolver>("createUnitResolver");
  const typescriptResolver = TypeScriptApi.createUnitResolver(
    { force: "kN", length: "cm" },
    { force: "N", length: "mm" },
  );
  const javascriptResolver = createJavaScriptResolver(
    { force: "kN", length: "cm" },
    { force: "N", length: "mm" },
  );
  const values = [0, 1, -2.5, Number.NaN, Number.POSITIVE_INFINITY];
  const methods = [
    "length",
    "area",
    "volume",
    "force",
    "moment",
    "lineLoad",
    "areaLoad",
    "volumeLoad",
    "stress",
    "translationalStiffness",
    "rotationalStiffness",
    "inertia",
    "sectionModulus",
  ] as const;

  assert.deepEqual(typescriptResolver.unitSystem, javascriptResolver.unitSystem);
  assert.deepEqual(typescriptResolver.sourceUnitSystem, javascriptResolver.sourceUnitSystem);
  assert.deepEqual(typescriptResolver.targetUnitSystem, javascriptResolver.targetUnitSystem);

  for (const method of methods) {
    for (const value of values) {
      assert.deepEqual(
        typescriptResolver[method](value),
        javascriptResolver[method](value),
        `${method} differs for ${String(value)}.`,
      );
    }
  }

  const typescriptIdentityResolver = TypeScriptApi.createUnitResolver(null);
  const javascriptIdentityResolver = createJavaScriptResolver(null);
  assert.equal(
    typescriptIdentityResolver.length === typescriptIdentityResolver.area,
    javascriptIdentityResolver.length === javascriptIdentityResolver.area,
  );
});

void test("generic check utilities match the live baseline", () => {
  const javascriptUtilizationCheck =
    baselineExport<typeof TypeScriptApi.utilizationCheck>("utilizationCheck");
  const javascriptGoverningCheck =
    baselineExport<typeof TypeScriptApi.governingCheck>("governingCheck");
  const options = {
    id: "capacity",
    description: "Capacity",
    demand: -12.3456789,
    capacity: 20,
    metadata: { method: "parity" },
  };
  const typescriptCheck = TypeScriptApi.utilizationCheck(options);
  const javascriptCheck = javascriptUtilizationCheck(options);

  assert.deepEqual(typescriptCheck, javascriptCheck);
  assert.deepEqual(
    TypeScriptApi.governingCheck([
      typescriptCheck,
      { ...typescriptCheck, id: "second", utilizationRatio: 0.9 },
    ]),
    javascriptGoverningCheck([
      javascriptCheck,
      { ...javascriptCheck, id: "second", utilizationRatio: 0.9 },
    ]),
  );
  assert.deepEqual(
    TypeScriptApi.uniqueStrings(["a", "", "a", null, "b"]),
    baselineExport<typeof TypeScriptApi.uniqueStrings>("uniqueStrings")(["a", "", "a", null, "b"]),
  );
});
